%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\91571\Desktop\Software\NBMiner_41.3_Win\address\cmd\networkchart\networkchart_20241212_022915_nblocks_10.csv
%
% Auto-generated by MATLAB on 2024-12-12 03:26:53

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time", "Height", "HashrateM", "CalculatedDifficultyM"];
opts.VariableTypes = ["datetime", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Time", "InputFormat", "yyyy/M/d H:mm:ss");

% Import the data
tbl = readtable("C:\Users\91571\Desktop\Software\NBMiner_41.3_Win\address\cmd\networkchart\networkchart_20241212_041723_nblocks_10.csv", opts);

%% Convert to output type
Time = tbl.Time;
Height = tbl.Height;
HashrateM = tbl.HashrateM;
CalculatedDifficultyM = tbl.CalculatedDifficultyM;

%% Clear temporary variables
clear opts tbl

t = tiledlayout(2, 2); 
nexttile;
plot(Time,HashrateM,'DatetimeTickFormat',"yyyy-MM-dd")
xlabel("UTC")
ylabel("hashrate MH")
title("BitcoinPoW hashrate chart")
set(gca, 'YScale', 'log');

nexttile;
plot(Time,CalculatedDifficultyM,'DatetimeTickFormat',"yyyy-MM-dd")
xlabel("UTC")
ylabel("difficulty M")
title("BitcoinPoW difficulty chart")
set(gca, 'YScale', 'log');

nexttile;
plot(Time,HashrateM,'DatetimeTickFormat',"yyyy-MM-dd")
xlabel("UTC")
ylabel("hashrate MH")
title("BitcoinPoW hashrate chart")

nexttile;
plot(Time,CalculatedDifficultyM,'DatetimeTickFormat',"yyyy-MM-dd")
xlabel("UTC")
ylabel("difficulty M")
title("BitcoinPoW difficulty chart")